### PR TITLE
fix issue with sort index

### LINKED ISSUE #16: Rendering inline listeners priority
**Describe the bug**
When rendering inline items the priority messes with the content, sometimes even deleting content

**The delta code which generates the Problem**
```
{"ops": [
  {"attributes": {"italic": true},"insert": "italic text"},
  {"attributes": {"link": "https://www.test.com/","bold": true},"insert": "link"},
  {"insert": "\n"}
]}
```
**The expected html output the delta should produce**
```
<p><em>italic text</em><a href="https://www.test.com/" target="_blank"><strong>link</strong></a></p>
```

**Expected behavior**
I expect the order of the inserts to be honored

**Additional context**
This bug also happens with other inline items;
I would like to help fix it but am unsure of the desired direction; It feels like we need to revisit the entire order of how inline things are rendered at the moment. Did you notice this before? Do you have a desired direction? Or do you consider this behavior as intended?

If you update output.php on line 40 & 41
```
<link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
<script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>
```
link will work on the demo page

### PR DESCRIPTION
**Pull request by nadar**
this closes #16

### CODE REVIEW

File: src/Line.php [hunk 1]
```diff
@@ -220,12 +220,15 @@ public function getAttribute($name)
      *
      * Certain elements needs to prepend values into the next element.
      *
+     * > Since version 1.3.3 the Line argument is required in order to ensure the correct index for the prepend element.
```
Comment (lode) [inline src/Line.php]: Shouldn't this use `@since` instead of `> Since`?

I guess `> ...` is used for the automatic documentation. But the rest of the code all uses `@since`, so it would be nice for the consistency.

File: tests/PrependInlineIndexTest.php [hunk 2]
```diff
@@ -0,0 +1,13 @@
+<?php
+namespace nadar\quill\tests;
+
+class PrependInlineIndexTest extends DeltaTestCase
+{
+    public $json = <<<'JSON'
+{"ops":[{"attributes":{"italic":true},"insert":"italic"},{"attributes":{"bold":true,"link":"https://nadar.io"},"insert":"link"},{"insert":"\n"}]}
```
Comment (lode) [inline tests/PrependInlineIndexTest.php]: I think it is nice to format these with each operation on its own line.

File: tests/PrependInlineIndexTest.php [hunk 3]
```diff
@@ -0,0 +1,13 @@
...
+JSON;
+
+    public $html = <<<'EOT'
+<p><em>italic</em><a href="https://nadar.io" target="_blank"><strong>link</strong></a></p>
```
Comment (lode) [inline tests/PrependInlineIndexTest.php]: And I rather like the feature of `DeltaTestCase` to remove newlines, would be nice to add new lines here for readability, like:

```html
<p>
<em>italic</em>
<a href="https://nadar.io" target="_blank"><strong>link</strong></a>
</p>
```

File: src/Line.php (hunk 1 above)
Comment (nadar) [reply src/Line.php]: I will add `{@since}` for the new property. Good catch

File: tests/PrependInlineIndexTest.php (hunk 2 above)
Comment (nadar) [reply tests/PrependInlineIndexTest.php]: sure. I just used the output.php "generate unit test" button. We could format the output there already.
