### PR TITLE
Check lists (#96)

### LINKED ISSUE #96: Support for checked/unchecked lists
**Describe the bug**
Quill provides a list type called "check". This type is adding a little square which can be checked or not ([Quill documentation](https://quilljs.com/docs/modules/toolbar)).

Image

When the render function is called, this error is raised : 

Image

**The delta code which generates the Problem**

```
{"insert":"\nThis is a checked element"},{"attributes":{"list":"checked"},"insert":"\n"},{"insert":"This is an unchecked element"},{"attributes":{"list":"unchecked"},"insert":"\n"}
```

**The expected html output the delta should produce**

A list with checkboxes (checked or not).

```
<style>
    ul {
      list-style: none;
      padding: 0;
    }
    li {
      display: flex;
      align-items: center;
    }
</style>
  
  
<ul>
  <li>
    <input type="checkbox" checked disabled>
    <label>This is a checked element</label>
  </li>
  <li>
    <input type="checkbox" disabled>
    <label>This is an unchecked element</label>
  </li>
</ul>
```

Image

### PR DESCRIPTION
**Pull request by EnzoKilm**
The current PR is related to the issue #96 where I was reporting a missing support for the "check" list type which creates "checked" and "unchecked" lists that were not handled resulting in an error.

Closes #96

### CODE REVIEW

File: src/listener/Lists.php [hunk 1]
```diff
@@ -104,11 +114,19 @@ public function render(Lexer $lexer)
...
+            $isCheck = in_array($this->getPickType($pick), [self::LIST_TYPE_CHECKED, self::LIST_TYPE_UNCHECKED], true);
+
             // create the opening OL/UL tag
             // opening tag process has been simplified, see https://github.com/nadar/quill-delta-parser/pull/33
             // and https://github.com/nadar/quill-delta-parser/issues/30
             if (!$isOpen) {
-                $output .= '<'.$this->getListAttribute($pick).'>'.PHP_EOL;
+                $output .= '<'.$this->getListAttribute($pick);
+                if ($isCheck) {
+                    $output .= ' class="list-unstyled"';
```
Comment (nadar) [inline src/listener/Lists.php:126]: please add the class as property of the Lists.php class, so people can override the listener with its own class name. thanks!

File: CHANGELOG.md [hunk 2]
```diff
@@ -4,6 +4,9 @@ All notable changes to this project will be documented in this file.
 
 This project adheres to [Semantic Versioning](http://semver.org/).
 
+## 3.4.3 (27. March 2025)
++ [#96](https://github.com/nadar/quill-delta-parser/issues/96) Addded HTML rendering for lists with type "checked" and "unchecked".
```
Comment (nadar) [inline CHANGELOG.md:8]: Its a new feature, so next release would be 3.5.0 thanks

**Review by nadar — CHANGES_REQUESTED** [review]
thanks, just something smal.

**Review by nadar — CHANGES_REQUESTED** [review]

File: src/listener/Lists.php [hunk 3]
```diff
@@ -41,6 +41,11 @@ class Lists extends BlockListener
      */
     public const LIST_TYPE_UNCHECKED = 'unchecked';
 
+    /**
+     * @var string
+     */
+    public const CLASS_CHECK_LIST = 'list-unstyled';
```
[the remark this answers is not in the document]
Comment (EnzoKilm) [reply src/listener/Lists.php]: My bad ! Fixed it !
